import { notFound } from "next/navigation";
import Browser from "@/components/Browser";
import type { ListingRow } from "@/lib/types";

/** Development-only page: the real UI with made-up listings, no database needed. */
export default function PreviewPage() {
  if (process.env.NODE_ENV === "production") notFound();
  return <Browser listings={SAMPLE} userId="me" names={{ me: "Stuart", partner: "Diana" }} />;
}

const now = Date.now();
const ago = (days: number) => new Date(now - days * 86400e3).toISOString();

const base = {
  source_listing_id: null,
  is_active: true,
  canonical_property_id: null,
  monthly_charges_eur: null,
  agency_fees_eur: null,
  land_sqm: null,
  total_floors: 6,
  postal_code: "75016",
  geocode_precise: true,
  ges_rating: null,
  has_cellar: true,
  is_furnished: null,
  floor_plan_url: null,
  agent_contact: null,
  ingest_channel: "email",
};

const SAMPLE: ListingRow[] = [
  {
    ...base,
    id: "1",
    source_site: "seloger",
    source_url: "https://www.seloger.com/",
    first_seen_at: ago(0.5),
    last_seen_at: ago(0.5),
    transaction_type: "buy",
    property_type: "apartment",
    title_fr: "Appartement 4 pièces 98 m² – Village d'Auteuil",
    title_en: "4-room apartment, 98 m² – Village d'Auteuil",
    price_eur: 1290000,
    price_per_sqm_eur: 13163,
    surface_sqm: 98,
    pieces_count: 4,
    bedroom_count: 2,
    floor: 3,
    has_elevator: true,
    quartier: "auteuil_sud",
    street_address: "rue Poussin",
    lat: 48.8478,
    lng: 2.2602,
    dpe_rating: "D",
    has_balcony: true,
    has_terrace: false,
    has_parking: false,
    description_fr:
      "Dans un bel immeuble ancien, au 3e étage avec ascenseur, appartement traversant de 98 m² comprenant une entrée, un double séjour donnant sur un balcon filant, une cuisine séparée, deux chambres, une salle de bains. Cave. Calme absolu.",
    description_en:
      "In a handsome period building, on the 3rd floor with lift, a 98 m² dual-aspect apartment with an entrance hall, a double living room opening onto a long balcony, a separate kitchen, two bedrooms and a bathroom. Cellar. Absolutely quiet.",
    photo_urls: [],
    agency_name: "Junot Passy-La Muette",
    interactions: [{ user_id: "partner", action: "favorite", note_text: null, created_at: ago(0.2) }],
  },
  {
    ...base,
    id: "2",
    source_site: "bienici",
    source_url: "https://www.bienici.com/",
    first_seen_at: ago(5),
    last_seen_at: ago(1),
    transaction_type: "rent",
    property_type: "apartment",
    title_fr: "3 pièces meublé 72 m² – La Muette",
    title_en: "Furnished 3-room, 72 m² – La Muette",
    price_eur: 2950,
    price_per_sqm_eur: 41,
    monthly_charges_eur: 180,
    surface_sqm: 72,
    pieces_count: 3,
    bedroom_count: 2,
    floor: 5,
    has_elevator: true,
    quartier: "muette",
    street_address: "12 rue de Passy",
    lat: 48.8577,
    lng: 2.2793,
    dpe_rating: "C",
    has_balcony: false,
    has_terrace: false,
    has_parking: false,
    is_furnished: true,
    description_fr: "Au 5e étage, lumineux 3 pièces meublé avec vue dégagée, proche métro La Muette et commerces de la rue de Passy.",
    description_en: "On the 5th floor, a bright furnished 3-room flat with open views, close to La Muette metro and the shops of rue de Passy.",
    photo_urls: [],
    agency_name: "Barnes",
    interactions: [{ user_id: "me", action: "note", note_text: "Near the school we liked", created_at: ago(0.5) }],
  },
  {
    ...base,
    id: "3",
    source_site: "bellesdemeures",
    source_url: "https://www.bellesdemeures.com/",
    first_seen_at: ago(1),
    last_seen_at: ago(1),
    transaction_type: "buy",
    property_type: "hotel_particulier",
    title_fr: "Hôtel particulier 320 m² avec jardin – Auteuil",
    title_en: "320 m² private mansion with garden – Auteuil",
    price_eur: 6900000,
    price_per_sqm_eur: 21563,
    surface_sqm: 320,
    land_sqm: 210,
    pieces_count: 9,
    bedroom_count: 5,
    floor: 0,
    total_floors: 3,
    has_elevator: false,
    quartier: "auteuil_nord",
    street_address: "villa Montmorency",
    lat: 48.8512,
    lng: 2.2585,
    dpe_rating: "E",
    has_balcony: false,
    has_terrace: true,
    has_parking: true,
    geocode_precise: false,
    description_fr: "Rare hôtel particulier sur trois niveaux avec jardin arboré de 210 m², garage et terrasse au dernier étage.",
    description_en: "A rare three-storey private mansion with a 210 m² tree-lined garden, garage and top-floor terrace.",
    photo_urls: [],
    agency_name: "Daniel Féau",
    interactions: [],
  },
  {
    ...base,
    id: "4",
    source_site: "pap",
    source_url: "https://www.pap.fr/",
    first_seen_at: ago(9),
    last_seen_at: ago(2),
    transaction_type: "buy",
    property_type: "apartment",
    title_fr: "2 pièces 45 m² – Auteuil Sud",
    title_en: "2-room, 45 m² – Auteuil Sud",
    price_eur: 520000,
    price_per_sqm_eur: 11556,
    surface_sqm: 45,
    pieces_count: 2,
    bedroom_count: 1,
    floor: 1,
    has_elevator: false,
    quartier: "auteuil_sud",
    street_address: "boulevard Exelmans",
    lat: 48.8425,
    lng: 2.2612,
    dpe_rating: "F",
    has_balcony: false,
    has_terrace: false,
    has_parking: false,
    description_fr: "Vente entre particuliers. 2 pièces au 1er étage sur cour, à rafraîchir.",
    description_en: "Private sale. Two-room flat on the 1st floor over a courtyard, needs refreshing.",
    photo_urls: [],
    agency_name: null,
    interactions: [{ user_id: "me", action: "reject", note_text: null, created_at: ago(1) }],
  },
];
